spring:
  application:
    name: IDENTITY-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Userdata
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084
