server:
  port: 8083
spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
          filters:
            - AuthenticationFilter
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
          filters:
            - AuthenticationFilter
        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
 
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
