spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: User
  application:
    name: UserService

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
